'use strict';
let profileWizard=null;
function profileCatalog(){const map=new Map();DEFAULT.forEach(r=>r.exercises.forEach(e=>{if(!map.has(e.id))map.set(e.id,e);}));return [...map.values()];}
function profileProposal(p){return window.GYM_PROFILE.generate(p,buildTrainingPlan(p.days,false),profileCatalog());}
function profileNotice(){return !state.profile&&!state.active&&!loadError?`<section class="profile-nudge"><div><strong>Tu gimnasio. Tu punto de partida.</strong><p>Completa tu perfil para preparar una propuesta según tu objetivo y disponibilidad.</p></div><button class="btn secondary" data-action="profile-start">Completar perfil</button></section>`:'';}
function beginProfile(){if(loadError){toast('Revisa primero la copia de tus datos en Rutina.');return;}profileWizard={step:1,draft:clone(state.profile||GYM_PROFILE.defaults(state.settings.weeklyGoal)),error:''};go('perfil');}
function profileOption(name,value,title,detail,checked,type='radio'){return `<label class="profile-option"><input type="${type}" name="${name}" value="${esc(value)}" ${checked?'checked':''}><span><strong>${esc(title)}</strong>${detail?`<small>${esc(detail)}</small>`:''}</span></label>`;}
function profileError(message){profileWizard.error=message;const el=$('#profile-error');if(el){el.textContent=message;el.hidden=false;el.focus();}}
function draftStep(form,validate=true){
 const f=new FormData(form),p=clone(profileWizard.draft),step=profileWizard.step;
 if(step===1){p.goal=f.get('goal');if(validate&&!Object.hasOwn(GYM_PROFILE.goals,p.goal)){profileError('Elige un objetivo.');return false;}}
 if(step===2){
   p.name=(f.get('name')||'').trim();p.age=f.get('age')===''?'':Number(f.get('age'));p.height=f.get('height')===''?null:Number(f.get('height'));p.weight=f.get('weight')===''?null:Number(f.get('weight'));p.experience=f.get('experience');
   if(validate&&!integer(p.age,18,100)){profileError('Introduce una edad entre 18 y 100 años. Estas propuestas están preparadas para adultos; para menores hace falta una rutina supervisada.');return false;}
   if(validate&&(p.name.length>60||p.height!==null&&(!Number.isFinite(p.height)||p.height<80||p.height>250)||p.weight!==null&&(!Number.isFinite(p.weight)||p.weight<25||p.weight>400)||!Object.hasOwn(GYM_PROFILE.levels,p.experience))){profileError('Revisa el nivel, la altura (80–250 cm) y el peso (25–400 kg). Puedes dejar altura y peso en blanco.');return false;}
 }
 if(step===3){
   p.days=Number(f.get('days'));p.minutes=Number(f.get('minutes'));p.equipment=f.getAll('equipment');p.avoid=f.getAll('avoid');
   if(validate&&!GYM_PROFILE.valid(p)){profileError('Elige entre 1 y 6 días, el tiempo de sesión y al menos un tipo de material del gimnasio.');return false;}
 }
 profileWizard.draft=p;profileWizard.error='';return true;
}
function proposalDetails(result){return `<div class="plan-preview-days">${result.routines.map(r=>`<details><summary><span><strong>${esc(r.day)} · ${esc(r.name)}</strong><small>${r.exercises.length} ejercicios · ${r.exercises.reduce((n,e)=>n+e.sets,0)} series · ≈ ${r.estimatedMinutes} min</small></span></summary><ul>${r.exercises.map(e=>`<li>${esc(e.name)}<span>${e.sets} × ${e.min}–${e.max} · ${e.rest} s</span></li>`).join('')}</ul>${r.cardioMinutes?`<p class="note">Al acabar: ${r.cardioMinutes} min de caminar a paso cómodo o bici suave, si te resulta cómodo. Incluidos en la estimación; puedes omitirlos.</p>`:''}</details>`).join('')}</div>${result.changes.length?`<details class="profile-adjustments"><summary>Adaptaciones de esta propuesta (${result.changes.length})</summary><ul>${result.changes.map(c=>`<li>${esc(c)}</li>`).join('')}</ul></details>`:''}${result.errors.length?`<div class="data-error" role="alert">${result.errors.map(e=>`<p>${esc(e)}</p>`).join('')}</div>`:''}`;}
function profileGuidance(p){return `${p.experience==='beginner'?'Empieza con cargas cómodas y aprende cada movimiento con el monitor. Deja unas 3 repeticiones en reserva.':p.experience==='returning'?'Durante las primeras semanas se limita el volumen a 2 series por ejercicio. Recupera la técnica y aumenta poco a poco.':'Elige cargas con las que puedas terminar cada serie manteniendo la técnica, dejando unas 2 repeticiones en reserva.'} ${p.goal==='strength'?'Los ejercicios principales usan más descanso; con experiencia, también un rango de repeticiones menor.':p.goal==='muscle'?'La propuesta prioriza las series de fuerza, dentro del tiempo disponible.':p.goal==='fatloss'?'La fuerza ayuda a mantener músculo. Se añade un final suave de actividad; el cambio de peso también depende de tus hábitos y alimentación.':'Se priorizan sesiones de volumen moderado que puedas mantener.'}`;}
function renderProfileWizard(){
 const {step,draft:p,error}=profileWizard,titles=['¿Qué quieres conseguir?','Conozcamos tu punto de partida.','Hagamos espacio en tu semana.','Así empieza tu plan.'];
 let content='';
 if(step===1)content=`<fieldset><legend>Tu objetivo principal</legend><div class="profile-options">${Object.entries(GYM_PROFILE.goals).map(([key,label])=>profileOption('goal',key,label,{muscle:'Desarrollar masa muscular con progresión.',strength:'Mejorar las cargas con técnica y descanso.',fatloss:'Combinar fuerza y algo de actividad adicional.',fitness:'Crear un hábito y mejorar tu condición física.'}[key],p.goal===key)).join('')}</div></fieldset>`;
 if(step===2)content=`<label for="profile-name">¿Cómo te llamas? <span class="muted">(opcional)</span></label><input id="profile-name" name="name" autocomplete="given-name" maxlength="60" value="${esc(p.name)}"><div class="profile-fields"><div><label for="profile-age">Edad</label><input id="profile-age" name="age" type="number" inputmode="numeric" min="18" max="100" step="1" required value="${p.age}"></div><div><label for="profile-height">Altura · cm <small>(opcional)</small></label><input id="profile-height" name="height" type="number" inputmode="decimal" min="80" max="250" step="any" value="${p.height??''}"></div><div><label for="profile-weight">Peso · kg <small>(opcional)</small></label><input id="profile-weight" name="weight" type="number" inputmode="decimal" min="25" max="400" step="any" value="${p.weight??''}"></div></div><p class="note">Peso y altura se guardan como referencia. Las cargas de los ejercicios las eliges tú según tu técnica y experiencia.</p><fieldset><legend>Tu experiencia</legend><div class="profile-options">${Object.entries(GYM_PROFILE.levels).map(([key,label])=>profileOption('experience',key,label,{beginner:'Volumen inicial moderado para aprender.',returning:'Un regreso progresivo durante las primeras semanas.',regular:'Ya conoces la técnica y tus cargas habituales.'}[key],p.experience===key)).join('')}</div></fieldset>`;
 if(step===3)content=`<div class="profile-fields"><div><label for="profile-days">Días por semana</label><select id="profile-days" name="days">${[1,2,3,4,5,6].map(n=>`<option value="${n}" ${n===p.days?'selected':''}>${n} ${n===1?'día':'días'}</option>`).join('')}</select></div><div><label for="profile-minutes">Tiempo por sesión</label><select id="profile-minutes" name="minutes">${[30,45,60,75,90].map(n=>`<option value="${n}" ${n===p.minutes?'selected':''}>${n} minutos</option>`).join('')}</select></div></div><p class="note">Incluye una estimación de calentamiento, descansos y cambios de ejercicio. Con menos tiempo se reducen series. Si empiezas, suele ser más fácil mantener 2–3 días; puedes elegir otra frecuencia.</p><fieldset><legend>Material disponible en tu gimnasio</legend><button type="button" class="textbtn" data-action="profile-all-equipment">Marcar gimnasio completo</button><div class="equipment-options">${Object.entries(GYM_PROFILE.equipment).map(([key,label])=>profileOption('equipment',key,label,'',p.equipment.includes(key),'checkbox')).join('')}</div></fieldset><p class="note">Marca solo lo que hay en tu gimnasio. Si una máquina está ocupada un día, usa «Cambiar ejercicio» durante el entrenamiento.</p><details class="profile-avoid"><summary>Ejercicios que prefieres evitar ${p.avoid.length?'('+p.avoid.length+')':''}</summary><p class="note">Se excluyen de la propuesta. Si hay dolor o una lesión, pide una valoración antes de buscar una alternativa.</p><div class="avoid-options">${[...profileCatalog(),...GYM_PROFILE.extra].map(e=>profileOption('avoid',e.id,e.name,'',p.avoid.includes(e.id),'checkbox')).join('')}</div></details>`;
 if(step===4){const result=profileProposal(p);content=`<div class="profile-summary"><span class="pill">GIMNASIO</span><h2>${esc(GYM_PROFILE.goals[p.goal])}</h2><p>${p.days} días / semana · hasta ${p.minutes} min · ${esc(GYM_PROFILE.levels[p.experience])}</p><p class="small muted">${p.equipment.map(k=>GYM_PROFILE.equipment[k]).join(' · ')}</p></div><p class="note">${esc(profileGuidance(p))}</p>${p.days===1?'<p class="plan-preserve">Un día es un punto de partida. Cuando puedas mantenerlo, dos días permiten repartir mejor el trabajo semanal.</p>':''}${p.days>3&&p.experience!=='regular'?'<p class="plan-preserve">Has elegido una frecuencia alta para empezar o volver. Si cuesta recuperarte, vuelve atrás y prueba con menos días.</p>':''}${proposalDetails(result)}<p class="note">Los minutos son aproximados: tus descansos y el ritmo del gimnasio pueden alargar la sesión. Plan general por reglas, editable en Rutina.</p>${!isFirstVisit?`<p class="plan-preserve">Al aplicar se conserva tu historial y se archiva el plan personalizado anterior.${state.active?' Tu sesión en curso sigue con sus ejercicios originales.':''}</p>`:''}<div class="profile-actions"><button type="button" class="btn secondary" data-action="profile-back">Revisar respuestas</button><button type="button" class="btn lime" data-action="profile-apply" ${result.errors.length?'disabled':''}>${state.profile?'Aplicar nueva rutina':'Guardar perfil y empezar'}</button></div>${!isFirstVisit?'<button type="button" class="textbtn" data-action="profile-save">Guardar solo el perfil, conservar mi rutina</button>':''}`;}
 return `<section class="onboarding"><div class="onboarding-top"><span class="pill">HECHO PARA TU GIMNASIO</span><button type="button" class="textbtn" data-action="profile-exit">${isFirstVisit?'Configurar después':'Cancelar'}</button></div><ol class="profile-steps" aria-label="Progreso del perfil">${['Objetivo','Sobre ti','Tu gimnasio','Tu plan'].map((label,i)=>`<li ${i+1===step?'aria-current="step"':''} class="${i+1<=step?'reached':''}"><span>${i+1<step?'✓':i+1}</span><small>${label}</small></li>`).join('')}</ol><p class="eyebrow">PASO ${step} DE 4</p><h1 tabindex="-1" id="profile-heading">${titles[step-1]}</h1><p class="onboarding-intro">${step===1?'Una rutina que encaje contigo, desde el primer día.':'Puedes revisar todo antes de guardar.'}</p><form id="profile-form" novalidate>${content}<p id="profile-error" class="data-error" role="alert" tabindex="-1" ${error?'':'hidden'}>${esc(error)}</p>${step<4?`<div class="profile-actions">${step>1?'<button type="button" class="btn secondary" data-action="profile-back">Atrás</button>':'<span></span>'}<button type="submit" class="btn lime">${step===3?'Ver mi propuesta':'Continuar'} <span aria-hidden="true">→</span></button></div>`:''}</form><p class="profile-privacy">${GYM_ACCOUNT.privacy()}</p></section>`;
}
function renderProfile(){
 if(profileWizard)return renderProfileWizard();
 const p=state.profile;
 if(!p)return pagehead('TU PUNTO DE PARTIDA','Tu perfil.')+`<section class="hero"><p class="eyebrow">ENTRENA EN TU GIMNASIO</p><h2>Un plan que encaje en tu semana.</h2><p class="onboarding-intro">Objetivo, experiencia, tiempo y material. Cuatro pasos para revisar una propuesta antes de aplicarla.</p><button class="btn lime" data-action="profile-start">Completar mi perfil</button><p class="note">Tus entrenamientos actuales se conservan.</p></section>`;
 const pending=!state.planProfile||GYM_PROFILE.preferences(p)!==GYM_PROFILE.preferences(state.planProfile);
 return pagehead('TU PUNTO DE PARTIDA',p.name?`El perfil de ${esc(p.name)}.`:'Tu perfil.',`<button class="btn lime" data-action="profile-start">Editar perfil</button>`)+`<div class="grid"><section class="card"><p class="eyebrow">OBJETIVO PRINCIPAL</p><h2>${esc(GYM_PROFILE.goals[p.goal])}</h2><dl class="profile-data"><div><dt>Experiencia</dt><dd>${esc(GYM_PROFILE.levels[p.experience])}</dd></div><div><dt>Disponibilidad</dt><dd>${p.days} días · ${p.minutes} min por sesión</dd></div><div><dt>Edad</dt><dd>${p.age} años</dd></div><div><dt>Altura</dt><dd>${p.height===null?'Sin indicar':num(p.height)+' cm'}</dd></div><div><dt>Peso de referencia</dt><dd>${p.weight===null?'Sin indicar':num(p.weight)+' kg'}</dd></div></dl><p class="note">Los datos corporales no calculan las cargas ni un diagnóstico. Actualízalos cuando lo necesites.</p></section><section class="card"><p class="eyebrow">TU GIMNASIO</p><h2>Material y preferencias</h2><div class="profile-tags">${p.equipment.map(k=>`<span class="pill">${esc(GYM_PROFILE.equipment[k])}</span>`).join('')}</div><p class="note">${p.avoid.length?p.avoid.length+' ejercicios excluidos de las propuestas automáticas.':'Sin ejercicios excluidos.'}</p>${p.avoid.length?`<details><summary>Ver exclusiones</summary><ul>${p.avoid.map(id=>`<li>${esc([...profileCatalog(),...GYM_PROFILE.extra].find(e=>e.id===id)?.name||id)}</li>`).join('')}</ul></details>`:''}<p class="note">${esc(profileGuidance(p))}</p></section></div>${pending?'<section class="profile-nudge"><div><strong>Preferencias guardadas, rutina conservada</strong><p>Tu rutina actual aún no refleja estas preferencias. Puedes revisar y aplicar una propuesta desde Editar perfil.</p></div></section>':''}<p class="profile-privacy">${GYM_ACCOUNT.privacy()}. El perfil se incluye al exportar tu copia desde Rutina.</p>`;
}
function finishProfile(apply){
 if(!profileWizard)return false;const p={...clone(profileWizard.draft),updatedAt:Date.now()};if(!GYM_PROFILE.valid(p))return false;
 const result=apply?profileProposal(p):null;if(result?.errors.length){profileError(result.errors.join(' '));return false;}
 const same=apply&&planSignature(state.routines)===planSignature(result.routines),snapshot=apply&&!same?currentPlanSnapshot():null;
 if(snapshot&&state.savedPlans.length>=20){profileError('Tienes 20 planes guardados. Elimina una copia de Planes anteriores antes de aplicar otra rutina, o guarda solo el perfil.');return false;}
 if(!commit(()=>{state.profile=p;state.onboardingDismissed=true;if(apply){if(snapshot)state.savedPlans.unshift(snapshot);if(!same){state.routines=result.routines;state.routines.forEach(r=>r.exercises.forEach(e=>e.slotId=uid()));}state.planProfile=clone(p);Object.assign(state.settings,{weeklyGoal:p.days,planDays:p.days,planRevision:1});}}))return false;
 profileWizard=null;isFirstVisit=false;selected=state.active?.routineId||nextRoutine();go(apply?'rutina':'perfil');toast(apply?'Perfil y rutina guardados.':'Perfil guardado. Tu rutina se conserva.');return true;
}
function focusProfileHeading(){document.getElementById('profile-heading')?.focus();window.scrollTo(0,0);}
document.addEventListener('submit',ev=>{if(ev.target.id!=='profile-form')return;ev.preventDefault();if(profileWizard.step<4&&draftStep(ev.target)){profileWizard.step++;render();focusProfileHeading();}});
document.addEventListener('click',ev=>{
 const b=ev.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='profile-start')beginProfile();
 if(a==='profile-back'&&profileWizard){if(profileWizard.step<4){draftStep($('#profile-form'),false);}profileWizard.step=Math.max(1,profileWizard.step-1);profileWizard.error='';render();focusProfileHeading();}
 if(a==='profile-exit'){if(isFirstVisit&&!commit(()=>{state.onboardingDismissed=true;}))return;profileWizard=null;isFirstVisit=false;go(state.profile?'perfil':'entrenar');}
 if(a==='profile-all-equipment')document.querySelectorAll('[name="equipment"]').forEach(e=>{e.checked=true;});
 if(a==='profile-apply')finishProfile(true);
 if(a==='profile-save')finishProfile(false);
});
